### ISSUE TITLE
how to add the phone number to the config file 

### ISSUE THREAD

**Issue by Agarshanan-Kasithasan** [badboysm890/Whatsapp-GPT3-BOT#1]
And make sure to add phone numbers to the config file and also hotword so it only gets triggered what they speak with certain hotword and leave empty to reply to everyone

can you show step by step how to do this. my both main.go and server.py was running and i did scan the QR code. although my whatsapp was connected , i couldnt see chatpgt in my whatsapp app on my iphone.

**Comment by badboysm890** [comment]
Sorry, seems like chat GPT blocked access to the website using Gecko or Chrome Driver via Playwright. I'm working on a fix and will soon release a update

**Comment by josevayas** [comment]
Hi @badboysm890 , great work man... I have the same question as @Agshanan ..... also...in the server.py I changed it to: 

BROWSER = PLAY.firefox.launch_persistent_context(
    user_data_dir="/tmp/playwright",
    headless=False,
    java_script_enabled=True,
) 

and ChatGPT opened without problem in the browser...however...I cant see it in my phone....any idea why?

Also I was able to add my phone number as follows:

{
"phoneNumbers": ["+1##########"],
"HotWord": ["Xword"],
"author": "badboy17g"
}

Thanks!

**Comment by vatsaaa** [comment]
> BROWSER = PLAY.firefox.launch_persistent_context(
> user_data_dir="/tmp/playwright",
> headless=False,
> java_script_enabled=True,
> )

The said fix to use "firefox" has not worked. Error as below:

```
MacBook-Pro Whatsapp-GPT3-BOT % python3 server.py
Traceback (most recent call last):
  File "/Users/.../mycgpt/Whatsapp-GPT3-BOT/server.py", line 76, in <module>
    start_browser()
  File "/Users/.../mycgpt/Whatsapp-GPT3-BOT/server.py", line 66, in start_browser
    PAGE.goto("https://chat.openai.com/")
  File "/Users/.../Library/Python/3.9/lib/python/site-packages/playwright/sync_api/_generated.py", line 8961, in goto
    self._sync(
  File "/Users/.../Library/Python/3.9/lib/python/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/Users/.../Library/Python/3.9/lib/python/site-packages/playwright/_impl/_page.py", line 491, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/Users/.../Library/Python/3.9/lib/python/site-packages/playwright/_impl/_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/Users/.../Library/Python/3.9/lib/python/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/Users/.../Library/Python/3.9/lib/python/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/Users/.../Library/Python/3.9/lib/python/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: SEC_ERROR_UNKNOWN_ISSUER
=========================== logs ===========================
navigating to "https://chat.openai.com/", waiting until "load"
============================================================
```

**Comment by badboysm890** [comment]
Looks like the Chat GPTis using Cloud flare which blocks all the bot based drivers 
will update a driver which is not detected by cloudflare

**Comment by badboysm890** [comment]
> Hi @badboysm890 , great work man... I have the same question as @Agshanan ..... also...in the server.py I changed it to:
> 
> BROWSER = PLAY.firefox.launch_persistent_context( user_data_dir="/tmp/playwright", headless=False, java_script_enabled=True, )
> 
> and ChatGPT opened without problem in the browser...however...I cant see it in my phone....any idea why?
> 
> Also I was able to add my phone number as follows:
> 
> { "phoneNumbers": ["+1##########"], "HotWord": ["Xword"], "author": "badboy17g" }
> 
> Thanks!

Scan the qr code, only phone numbers in the config will be replied with the chat gpt replies, and also the. hot word should match
